# coding: utf-8

"""
    Omnuis-API astu specificatioin

    Интеграционный сервис АИС КИС Баланс

    The version of the OpenAPI document: 2.0
    Contact: e-vasilyev@it-serv.ru
    Generated by: https://openapi-generator.tech
"""


from fastapi import FastAPI

from openapi_server.apis.astu_api import router as AstuApiRouter

app = FastAPI(
    title="Omnuis-API astu specificatioin",
    description="Интеграционный сервис АИС КИС Баланс",
    version="2.0",
)

app.include_router(AstuApiRouter)
