@startuml
title Сверка данных КА ЮЛ
start
:Флагман передал\nинформацию по КА;
:Выполнен поиск атрибутов\nпереданного КА в БД Омниус;
if (Есть КА с\nналогичным кодом\nфлагмана) then (Нет)
    if (Есть КА с\nаналогичным ИНН КПП) then (Нет)
        #palegreen :Создать КА\nс полученными\nпараметрами;
    else (Да)
        #pink :Ошибка уникальности\nКА по ИНН,КПП;
        stop
    endif
else (Да)
    :Проверка уникальности\nкодов флагмана\nOmnius;
    if (Более 1 КА с\nэквивалентным\nкодом флагмана\nOmnius) then (Да)
        #pink :Ошибка уникальности\nКА по коду флагмана;
        stop
    else (Нет)
        #palegreen :При совпадение ИНН,КПП\nОбновление\nвсей НСИ КА;
    endif
endif
:Формирование лога ошибок;
stop
@endumll