# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ConsumersRequestBodyParams(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConsumersRequestBodyParams - a model defined in OpenAPI

        type: The type of this ConsumersRequestBodyParams [Optional].
        date_begin: The date_begin of this ConsumersRequestBodyParams [Optional].
        date_end: The date_end of this ConsumersRequestBodyParams [Optional].
        consumer_id: The consumer_id of this ConsumersRequestBodyParams [Optional].
        service_location_id: The service_location_id of this ConsumersRequestBodyParams [Optional].
        system_state: The system_state of this ConsumersRequestBodyParams [Optional].
    """

    type: Optional[str] = Field(alias="type", default=None)
    date_begin: Optional[date] = Field(alias="Date_begin", default=None)
    date_end: Optional[date] = Field(alias="Date_end", default=None)
    consumer_id: Optional[List[str]] = Field(alias="ConsumerID", default=None)
    service_location_id: Optional[List[str]] = Field(alias="ServiceLocationID", default=None)
    system_state: Optional[List[str]] = Field(alias="SystemState", default=None)

ConsumersRequestBodyParams.update_forward_refs()
