# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.consumers_inner_usage_points_inner import ConsumersInnerUsagePointsInner
from openapi_server.models.geometry import Geometry


class ConsumersInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ConsumersInner - a model defined in OpenAPI

        action_type: The action_type of this ConsumersInner [Optional].
        consumer_id: The consumer_id of this ConsumersInner [Optional].
        consumer_name: The consumer_name of this ConsumersInner [Optional].
        consumer_type: The consumer_type of this ConsumersInner [Optional].
        contract: The contract of this ConsumersInner [Optional].
        requets_number: The requets_number of this ConsumersInner [Optional].
        service_location_id: The service_location_id of this ConsumersInner [Optional].
        name: The name of this ConsumersInner [Optional].
        organization_id: The organization_id of this ConsumersInner [Optional].
        object_status: The object_status of this ConsumersInner [Optional].
        fias_id: The fias_id of this ConsumersInner [Optional].
        address: The address of this ConsumersInner [Optional].
        region: The region of this ConsumersInner [Optional].
        district: The district of this ConsumersInner [Optional].
        city: The city of this ConsumersInner [Optional].
        street: The street of this ConsumersInner [Optional].
        house: The house of this ConsumersInner [Optional].
        room: The room of this ConsumersInner [Optional].
        remark: The remark of this ConsumersInner [Optional].
        cadaster: The cadaster of this ConsumersInner [Optional].
        max_power: The max_power of this ConsumersInner [Optional].
        reliability_category: The reliability_category of this ConsumersInner [Optional].
        phone: The phone of this ConsumersInner [Optional].
        residents_count: The residents_count of this ConsumersInner [Optional].
        service_disp_category: The service_disp_category of this ConsumersInner [Optional].
        num_of_storeys: The num_of_storeys of this ConsumersInner [Optional].
        stand_by_capacity: The stand_by_capacity of this ConsumersInner [Optional].
        significance: The significance of this ConsumersInner [Optional].
        service_contingency_catagory: The service_contingency_catagory of this ConsumersInner [Optional].
        in_charge_full_name: The in_charge_full_name of this ConsumersInner [Optional].
        emergency_power_reserve: The emergency_power_reserve of this ConsumersInner [Optional].
        techno_power_reserve: The techno_power_reserve of this ConsumersInner [Optional].
        techno_power_reserve_duration: The techno_power_reserve_duration of this ConsumersInner [Optional].
        geometry: The geometry of this ConsumersInner [Optional].
        usage_points: The usage_points of this ConsumersInner [Optional].
    """

    action_type: Optional[str] = Field(alias="ActionType", default=None)
    consumer_id: Optional[str] = Field(alias="ConsumerId", default=None)
    consumer_name: Optional[str] = Field(alias="ConsumerName", default=None)
    consumer_type: Optional[str] = Field(alias="ConsumerType", default=None)
    contract: Optional[str] = Field(alias="Contract", default=None)
    requets_number: Optional[str] = Field(alias="RequetsNumber", default=None)
    service_location_id: Optional[str] = Field(alias="ServiceLocationId", default=None)
    name: Optional[str] = Field(alias="Name", default=None)
    organization_id: Optional[str] = Field(alias="OrganizationId", default=None)
    object_status: Optional[str] = Field(alias="ObjectStatus", default=None)
    fias_id: Optional[str] = Field(alias="FiasId", default=None)
    address: Optional[str] = Field(alias="Address", default=None)
    region: Optional[str] = Field(alias="Region", default=None)
    district: Optional[str] = Field(alias="District", default=None)
    city: Optional[str] = Field(alias="City", default=None)
    street: Optional[str] = Field(alias="Street", default=None)
    house: Optional[str] = Field(alias="House", default=None)
    room: Optional[str] = Field(alias="Room", default=None)
    remark: Optional[str] = Field(alias="Remark", default=None)
    cadaster: Optional[str] = Field(alias="Cadaster", default=None)
    max_power: Optional[str] = Field(alias="MaxPower", default=None)
    reliability_category: Optional[str] = Field(alias="ReliabilityCategory", default=None)
    phone: Optional[str] = Field(alias="Phone", default=None)
    residents_count: Optional[str] = Field(alias="ResidentsCount", default=None)
    service_disp_category: Optional[str] = Field(alias="ServiceDispCategory", default=None)
    num_of_storeys: Optional[str] = Field(alias="NumOfStoreys", default=None)
    stand_by_capacity: Optional[str] = Field(alias="StandByCapacity", default=None)
    significance: Optional[str] = Field(alias="Significance", default=None)
    service_contingency_catagory: Optional[str] = Field(alias="ServiceContingencyCatagory", default=None)
    in_charge_full_name: Optional[str] = Field(alias="InChargeFullName", default=None)
    emergency_power_reserve: Optional[str] = Field(alias="EmergencyPowerReserve", default=None)
    techno_power_reserve: Optional[str] = Field(alias="TechnoPowerReserve", default=None)
    techno_power_reserve_duration: Optional[str] = Field(alias="TechnoPowerReserveDuration", default=None)
    geometry: Optional[Geometry] = Field(alias="Geometry", default=None)
    usage_points: Optional[List[ConsumersInnerUsagePointsInner]] = Field(alias="UsagePoints", default=None)

ConsumersInner.update_forward_refs()
