# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.disconnection_reconnection_disconnection_list_inner_usage_points_inner import DisconnectionReconnectionDisconnectionListInnerUsagePointsInner


class DisconnectionReconnectionDisconnectionListInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DisconnectionReconnectionDisconnectionListInner - a model defined in OpenAPI

        action_type: The action_type of this DisconnectionReconnectionDisconnectionListInner [Optional].
        discconection_id: The discconection_id of this DisconnectionReconnectionDisconnectionListInner [Optional].
        description: The description of this DisconnectionReconnectionDisconnectionListInner [Optional].
        type: The type of this DisconnectionReconnectionDisconnectionListInner [Optional].
        reason: The reason of this DisconnectionReconnectionDisconnectionListInner [Optional].
        date: The date of this DisconnectionReconnectionDisconnectionListInner [Optional].
        area: The area of this DisconnectionReconnectionDisconnectionListInner [Optional].
        initiator: The initiator of this DisconnectionReconnectionDisconnectionListInner [Optional].
        performer: The performer of this DisconnectionReconnectionDisconnectionListInner [Optional].
        consumer_id: The consumer_id of this DisconnectionReconnectionDisconnectionListInner [Optional].
        usage_points: The usage_points of this DisconnectionReconnectionDisconnectionListInner [Optional].
    """

    action_type: Optional[str] = Field(alias="ActionType", default=None)
    discconection_id: Optional[str] = Field(alias="DiscconectionId", default=None)
    description: Optional[str] = Field(alias="Description", default=None)
    type: Optional[str] = Field(alias="Type", default=None)
    reason: Optional[str] = Field(alias="Reason", default=None)
    date: Optional[date] = Field(alias="Date", default=None)
    area: Optional[str] = Field(alias="Area", default=None)
    initiator: Optional[str] = Field(alias="Initiator", default=None)
    performer: Optional[str] = Field(alias="Performer", default=None)
    consumer_id: Optional[str] = Field(alias="ConsumerId", default=None)
    usage_points: Optional[List[DisconnectionReconnectionDisconnectionListInnerUsagePointsInner]] = Field(alias="UsagePoints", default=None)

DisconnectionReconnectionDisconnectionListInner.update_forward_refs()
