# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class DisconnectionReconnectionRequestBodyParams(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DisconnectionReconnectionRequestBodyParams - a model defined in OpenAPI

        date_begin: The date_begin of this DisconnectionReconnectionRequestBodyParams.
        date_end: The date_end of this DisconnectionReconnectionRequestBodyParams.
    """

    date_begin: date = Field(alias="Date_begin")
    date_end: date = Field(alias="Date_end")

DisconnectionReconnectionRequestBodyParams.update_forward_refs()
