# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.disconnection_reconnection_request_body_params import DisconnectionReconnectionRequestBodyParams
from openapi_server.models.service import Service


class DisconnectionReconnectionRequestBody(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DisconnectionReconnectionRequestBody - a model defined in OpenAPI

        service: The service of this DisconnectionReconnectionRequestBody.
        params: The params of this DisconnectionReconnectionRequestBody.
    """

    service: Service = Field(alias="Service")
    params: DisconnectionReconnectionRequestBodyParams = Field(alias="Params")

DisconnectionReconnectionRequestBody.update_forward_refs()
