# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class EndDeviceRequestBodyParams(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EndDeviceRequestBodyParams - a model defined in OpenAPI

        consumption_type: The consumption_type of this EndDeviceRequestBodyParams [Optional].
        device_type: The device_type of this EndDeviceRequestBodyParams [Optional].
        date_begin: The date_begin of this EndDeviceRequestBodyParams [Optional].
        date_end: The date_end of this EndDeviceRequestBodyParams [Optional].
        usage_point_id: The usage_point_id of this EndDeviceRequestBodyParams [Optional].
        device_id_id: The device_id_id of this EndDeviceRequestBodyParams [Optional].
        system_state: The system_state of this EndDeviceRequestBodyParams [Optional].
    """

    consumption_type: Optional[str] = Field(alias="ConsumptionType", default=None)
    device_type: Optional[List[str]] = Field(alias="DeviceType", default=None)
    date_begin: Optional[date] = Field(alias="Date_begin", default=None)
    date_end: Optional[date] = Field(alias="Date_end", default=None)
    usage_point_id: Optional[List[str]] = Field(alias="UsagePointID", default=None)
    device_id_id: Optional[List[str]] = Field(alias="DeviceIdID", default=None)
    system_state: Optional[List[str]] = Field(alias="SystemState", default=None)

EndDeviceRequestBodyParams.update_forward_refs()
