# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class EndDevicesInnerMeasurePointsInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EndDevicesInnerMeasurePointsInner - a model defined in OpenAPI

        id: The id of this EndDevicesInnerMeasurePointsInner [Optional].
        description: The description of this EndDevicesInnerMeasurePointsInner [Optional].
        type: The type of this EndDevicesInnerMeasurePointsInner [Optional].
    """

    id: Optional[str] = Field(alias="id", default=None)
    description: Optional[str] = Field(alias="description", default=None)
    type: Optional[str] = Field(alias="type", default=None)

EndDevicesInnerMeasurePointsInner.update_forward_refs()
