# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.end_devices_inner_measure_points_inner import EndDevicesInnerMeasurePointsInner
from openapi_server.models.geometry import Geometry


class EndDevicesInner(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EndDevicesInner - a model defined in OpenAPI

        action_type: The action_type of this EndDevicesInner [Optional].
        end_device_id: The end_device_id of this EndDevicesInner [Optional].
        name: The name of this EndDevicesInner [Optional].
        organization_id: The organization_id of this EndDevicesInner [Optional].
        device_type: The device_type of this EndDevicesInner [Optional].
        serial_number: The serial_number of this EndDevicesInner [Optional].
        is_amr: The is_amr of this EndDevicesInner [Optional].
        is_commercial: The is_commercial of this EndDevicesInner [Optional].
        device_status: The device_status of this EndDevicesInner [Optional].
        belonging_type: The belonging_type of this EndDevicesInner [Optional].
        usage_point_id: The usage_point_id of this EndDevicesInner [Optional].
        substation_code_tm: The substation_code_tm of this EndDevicesInner [Optional].
        bay_code_tm: The bay_code_tm of this EndDevicesInner [Optional].
        line_code_tm: The line_code_tm of this EndDevicesInner [Optional].
        tower_code_tm: The tower_code_tm of this EndDevicesInner [Optional].
        device_location: The device_location of this EndDevicesInner [Optional].
        geometry: The geometry of this EndDevicesInner [Optional].
        measure_points: The measure_points of this EndDevicesInner [Optional].
    """

    action_type: Optional[str] = Field(alias="ActionType", default=None)
    end_device_id: Optional[str] = Field(alias="EndDeviceId", default=None)
    name: Optional[str] = Field(alias="Name", default=None)
    organization_id: Optional[str] = Field(alias="OrganizationID", default=None)
    device_type: Optional[str] = Field(alias="DeviceType", default=None)
    serial_number: Optional[str] = Field(alias="SerialNumber", default=None)
    is_amr: Optional[str] = Field(alias="isAMR", default=None)
    is_commercial: Optional[str] = Field(alias="IsCommercial", default=None)
    device_status: Optional[str] = Field(alias="DeviceStatus", default=None)
    belonging_type: Optional[str] = Field(alias="BelongingType", default=None)
    usage_point_id: Optional[str] = Field(alias="UsagePointID", default=None)
    substation_code_tm: Optional[str] = Field(alias="SubstationCodeTM", default=None)
    bay_code_tm: Optional[str] = Field(alias="BayCodeTM", default=None)
    line_code_tm: Optional[str] = Field(alias="LineCodeTM", default=None)
    tower_code_tm: Optional[str] = Field(alias="TowerCodeTM", default=None)
    device_location: Optional[str] = Field(alias="DeviceLocation", default=None)
    geometry: Optional[Geometry] = Field(alias="geometry", default=None)
    measure_points: Optional[List[EndDevicesInnerMeasurePointsInner]] = Field(alias="MeasurePoints", default=None)

EndDevicesInner.update_forward_refs()
