# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from openapi_server.models.end_device_request_body_params import EndDeviceRequestBodyParams
from openapi_server.models.service import Service


class EndDeviceRequestBody(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    EndDeviceRequestBody - a model defined in OpenAPI

        service: The service of this EndDeviceRequestBody.
        params: The params of this EndDeviceRequestBody.
    """

    service: Service = Field(alias="Service")
    params: EndDeviceRequestBodyParams = Field(alias="Params")

EndDeviceRequestBody.update_forward_refs()
