# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ServiceLocationAddress(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceLocationAddress - a model defined in OpenAPI

        address: The address of this ServiceLocationAddress [Optional].
        region: The region of this ServiceLocationAddress [Optional].
        district: The district of this ServiceLocationAddress [Optional].
        city: The city of this ServiceLocationAddress [Optional].
        street: The street of this ServiceLocationAddress [Optional].
        house: The house of this ServiceLocationAddress [Optional].
    """

    address: Optional[str] = Field(alias="Address", default=None)
    region: Optional[str] = Field(alias="Region", default=None)
    district: Optional[str] = Field(alias="District", default=None)
    city: Optional[str] = Field(alias="City", default=None)
    street: Optional[str] = Field(alias="Street", default=None)
    house: Optional[str] = Field(alias="House", default=None)

ServiceLocationAddress.update_forward_refs()
