# coding: utf-8

"""
    Omnuis-API astu specificatioin

    Интеграционный сервис АИС КИС Баланс

    The version of the OpenAPI document: 2.0
    Contact: e-vasilyev@it-serv.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.astu_api import AstuApi  # noqa: E501


class TestAstuApi(unittest.TestCase):
    """AstuApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AstuApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_process_objects(self) -> None:
        """Test case for process_objects

        Отправка объектов на обработку  # noqa: E501
        """
        pass

    def test_search_objects(self) -> None:
        """Test case for search_objects

        Запрос поиска объектов  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
