# coding: utf-8

"""
    Omnuis-API astu specificatioin

    Интеграционный сервис АИС КИС Баланс

    The version of the OpenAPI document: 2.0
    Contact: e-vasilyev@it-serv.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.end_devices_inner_measure_points_inner import EndDevicesInnerMeasurePointsInner  # noqa: E501

class TestEndDevicesInnerMeasurePointsInner(unittest.TestCase):
    """EndDevicesInnerMeasurePointsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EndDevicesInnerMeasurePointsInner:
        """Test EndDevicesInnerMeasurePointsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EndDevicesInnerMeasurePointsInner`
        """
        model = EndDevicesInnerMeasurePointsInner()  # noqa: E501
        if include_optional:
            return EndDevicesInnerMeasurePointsInner(
                id = 'string',
                description = 'string',
                type = 'string'
            )
        else:
            return EndDevicesInnerMeasurePointsInner(
        )
        """

    def testEndDevicesInnerMeasurePointsInner(self):
        """Test EndDevicesInnerMeasurePointsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
