# coding: utf-8

"""
    Omnuis-API astu specificatioin

    Интеграционный сервис АИС КИС Баланс

    The version of the OpenAPI document: 2.0
    Contact: e-vasilyev@it-serv.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.usage_point import UsagePoint  # noqa: E501

class TestUsagePoint(unittest.TestCase):
    """UsagePoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsagePoint:
        """Test UsagePoint
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsagePoint`
        """
        model = UsagePoint()  # noqa: E501
        if include_optional:
            return UsagePoint(
                service = openapi_client.models.service.Service(
                    service_type = 'Disconnection_Reconnection_list', 
                    filial = '23', 
                    area = [
                        '23'
                        ], ),
                usage_point_id = '4564566',
                service_location_id = '1233443',
                substation_code_tm = 'TP010-00032333',
                transformer_name = 'Т-1',
                bay_code_tm = 'TP010-00032333-16-01-01',
                bay_name = 'яч. 1 ф. ВЛ 0,4 кВ',
                line_code_tm = 'VN004-00003234',
                line_name = 'ВЛ 0,4 кВ 1',
                tower_code_tm = 'VN004-00003234-001-1001',
                tower_name = 'Опора 1'
            )
        else:
            return UsagePoint(
                service = openapi_client.models.service.Service(
                    service_type = 'Disconnection_Reconnection_list', 
                    filial = '23', 
                    area = [
                        '23'
                        ], ),
                usage_point_id = '4564566',
                substation_code_tm = 'TP010-00032333',
        )
        """

    def testUsagePoint(self):
        """Test UsagePoint"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
