# coding: utf-8

"""
    Omnuis-API astu specificatioin

    Интеграционный сервис АИС КИС Баланс

    The version of the OpenAPI document: 2.0
    Contact: e-vasilyev@it-serv.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.consumers_inner_usage_points_inner import ConsumersInnerUsagePointsInner  # noqa: E501

class TestConsumersInnerUsagePointsInner(unittest.TestCase):
    """ConsumersInnerUsagePointsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConsumersInnerUsagePointsInner:
        """Test ConsumersInnerUsagePointsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConsumersInnerUsagePointsInner`
        """
        model = ConsumersInnerUsagePointsInner()  # noqa: E501
        if include_optional:
            return ConsumersInnerUsagePointsInner(
                action_type = 'INSERT',
                usage_point_id = '1233455',
                name = 'Описание точки поставки',
                organization_id = '2308',
                is_sdp = True,
                voltage_level = 'НН',
                voltage_class = '0.4',
                service_location_id = '1233443',
                substation_code_tm = 'TP010-00032333',
                substation_name = 'ТП 3004',
                transformer_name = 'Т-1',
                bay_code_tm = 'TP010-00032333-16-01-01',
                bay_name = 'яч. 1 ф. ВЛ 0,4 кВ',
                line_code_tm = 'VN004-00003234',
                line_name = 'ВЛ 0,4 кВ 1',
                tower_code_tm = 'VN004-00003234-001-1001',
                tower_name = 'Опора 1',
                remark = 'На кабельных наконечниках отходящего фидера 0,4 кВ ф. 1 ТП-3004',
                geometry = openapi_client.models.geometry.Geometry(
                    type = 'Point', 
                    coordinates = [
                        openapi_client.models.geometry_coordinates_inner.Geometry_Coordinates_inner(
                            x = 1.337, 
                            y = 1.337, )
                        ], )
            )
        else:
            return ConsumersInnerUsagePointsInner(
        )
        """

    def testConsumersInnerUsagePointsInner(self):
        """Test ConsumersInnerUsagePointsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
