# coding: utf-8

"""
    Omnuis-API astu specificatioin

    Интеграционный сервис АИС КИС Баланс

    The version of the OpenAPI document: 2.0
    Contact: e-vasilyev@it-serv.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.consumers_request_body import ConsumersRequestBody  # noqa: E501

class TestConsumersRequestBody(unittest.TestCase):
    """ConsumersRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConsumersRequestBody:
        """Test ConsumersRequestBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConsumersRequestBody`
        """
        model = ConsumersRequestBody()  # noqa: E501
        if include_optional:
            return ConsumersRequestBody(
                service = openapi_client.models.service.Service(
                    service_type = 'Disconnection_Reconnection_list', 
                    filial = '23', 
                    area = [
                        '23'
                        ], ),
                params = openapi_client.models.consumers_request_body_params.Consumers_request_body_Params(
                    type = 'ФЛ', 
                    date_begin = 'Wed Mar 01 03:00:00 MSK 2023', 
                    date_end = 'Wed Mar 01 03:00:00 MSK 2023', 
                    consumer_id = [
                        '10000012, 100000013'
                        ], 
                    service_location_id = [
                        '20000012, 200000013'
                        ], 
                    system_state = [
                        'Действующий, Проект'
                        ], )
            )
        else:
            return ConsumersRequestBody(
                service = openapi_client.models.service.Service(
                    service_type = 'Disconnection_Reconnection_list', 
                    filial = '23', 
                    area = [
                        '23'
                        ], ),
                params = openapi_client.models.consumers_request_body_params.Consumers_request_body_Params(
                    type = 'ФЛ', 
                    date_begin = 'Wed Mar 01 03:00:00 MSK 2023', 
                    date_end = 'Wed Mar 01 03:00:00 MSK 2023', 
                    consumer_id = [
                        '10000012, 100000013'
                        ], 
                    service_location_id = [
                        '20000012, 200000013'
                        ], 
                    system_state = [
                        'Действующий, Проект'
                        ], ),
        )
        """

    def testConsumersRequestBody(self):
        """Test ConsumersRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
