# coding: utf-8

"""
    Omnuis-API astu specificatioin

    Интеграционный сервис АИС КИС Баланс

    The version of the OpenAPI document: 2.0
    Contact: e-vasilyev@it-serv.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.disconnection_reconnection_disconnection_list_inner_usage_points_inner import DisconnectionReconnectionDisconnectionListInnerUsagePointsInner  # noqa: E501

class TestDisconnectionReconnectionDisconnectionListInnerUsagePointsInner(unittest.TestCase):
    """DisconnectionReconnectionDisconnectionListInnerUsagePointsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DisconnectionReconnectionDisconnectionListInnerUsagePointsInner:
        """Test DisconnectionReconnectionDisconnectionListInnerUsagePointsInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DisconnectionReconnectionDisconnectionListInnerUsagePointsInner`
        """
        model = DisconnectionReconnectionDisconnectionListInnerUsagePointsInner()  # noqa: E501
        if include_optional:
            return DisconnectionReconnectionDisconnectionListInnerUsagePointsInner(
                action_type = 'string',
                name = 'string',
                organization_id = 'string',
                is_sdp = 'boolean',
                voltage_level = 'string',
                voltage_class = 'string',
                service_location_id = 'string',
                substation_code_tm = 'string',
                substation_name = 'string',
                transformer_name = 'string',
                bay_code_tm = 'string',
                bay_name = 'string',
                line_code_tm = 'string',
                line_name = 'string',
                tower_code_tm = 'string',
                tower_name = 'string',
                remark = 'string',
                geometry = openapi_client.models.geometry.Geometry(
                    type = 'Point', 
                    coordinates = [
                        openapi_client.models.geometry_coordinates_inner.Geometry_Coordinates_inner(
                            x = 1.337, 
                            y = 1.337, )
                        ], )
            )
        else:
            return DisconnectionReconnectionDisconnectionListInnerUsagePointsInner(
        )
        """

    def testDisconnectionReconnectionDisconnectionListInnerUsagePointsInner(self):
        """Test DisconnectionReconnectionDisconnectionListInnerUsagePointsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
