# coding: utf-8

"""
    Omnuis-API astu specificatioin

    Интеграционный сервис АИС КИС Баланс

    The version of the OpenAPI document: 2.0
    Contact: e-vasilyev@it-serv.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.service_location import ServiceLocation  # noqa: E501

class TestServiceLocation(unittest.TestCase):
    """ServiceLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceLocation:
        """Test ServiceLocation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceLocation`
        """
        model = ServiceLocation()  # noqa: E501
        if include_optional:
            return ServiceLocation(
                service = openapi_client.models.service.Service(
                    service_type = 'Disconnection_Reconnection_list', 
                    filial = '23', 
                    area = [
                        '23'
                        ], ),
                consumer_id = '4564566',
                service_location_id = '1233443',
                address = openapi_client.models.service_location_address.ServiceLocation_Address(
                    address = 'обл Московская , р-н Истринский, г Истра, д.1', 
                    region = 'Московская обл.', 
                    district = 'Истринский р-н', 
                    city = 'г. Истра', 
                    street = 'ул. Усадебная', 
                    house = 'д.1', ),
                cadatster = openapi_client.models.service_location_cadatster.ServiceLocation_Cadatster(
                    cadaster = '77:232423443:14', ),
                geometry = openapi_client.models.geometry.Geometry(
                    type = 'Point', 
                    coordinates = [
                        openapi_client.models.geometry_coordinates_inner.Geometry_Coordinates_inner(
                            x = 1.337, 
                            y = 1.337, )
                        ], )
            )
        else:
            return ServiceLocation(
                service = openapi_client.models.service.Service(
                    service_type = 'Disconnection_Reconnection_list', 
                    filial = '23', 
                    area = [
                        '23'
                        ], ),
                consumer_id = '4564566',
                service_location_id = '1233443',
                geometry = openapi_client.models.geometry.Geometry(
                    type = 'Point', 
                    coordinates = [
                        openapi_client.models.geometry_coordinates_inner.Geometry_Coordinates_inner(
                            x = 1.337, 
                            y = 1.337, )
                        ], ),
        )
        """

    def testServiceLocation(self):
        """Test ServiceLocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
