# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.disconnection_reconnection_disconnection_list_inner import DisconnectionReconnectionDisconnectionListInner
from openapi_server.models.disconnection_reconnection_reconnection_list_inner import DisconnectionReconnectionReconnectionListInner
from openapi_server import util


class DisconnectionReconnection(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, disconnection_list: List[DisconnectionReconnectionDisconnectionListInner]=None, reconnection_list: List[DisconnectionReconnectionReconnectionListInner]=None):
        """DisconnectionReconnection - a model defined in OpenAPI

        :param disconnection_list: The disconnection_list of this DisconnectionReconnection.
        :param reconnection_list: The reconnection_list of this DisconnectionReconnection.
        """
        self.openapi_types = {
            'disconnection_list': List[DisconnectionReconnectionDisconnectionListInner],
            'reconnection_list': List[DisconnectionReconnectionReconnectionListInner]
        }

        self.attribute_map = {
            'disconnection_list': 'DisconnectionList',
            'reconnection_list': 'ReconnectionList'
        }

        self._disconnection_list = disconnection_list
        self._reconnection_list = reconnection_list

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DisconnectionReconnection':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Disconnection_Reconnection of this DisconnectionReconnection.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def disconnection_list(self):
        """Gets the disconnection_list of this DisconnectionReconnection.

        Массив данных по отключениям

        :return: The disconnection_list of this DisconnectionReconnection.
        :rtype: List[DisconnectionReconnectionDisconnectionListInner]
        """
        return self._disconnection_list

    @disconnection_list.setter
    def disconnection_list(self, disconnection_list):
        """Sets the disconnection_list of this DisconnectionReconnection.

        Массив данных по отключениям

        :param disconnection_list: The disconnection_list of this DisconnectionReconnection.
        :type disconnection_list: List[DisconnectionReconnectionDisconnectionListInner]
        """

        self._disconnection_list = disconnection_list

    @property
    def reconnection_list(self):
        """Gets the reconnection_list of this DisconnectionReconnection.

        Массив данных по возобновлению

        :return: The reconnection_list of this DisconnectionReconnection.
        :rtype: List[DisconnectionReconnectionReconnectionListInner]
        """
        return self._reconnection_list

    @reconnection_list.setter
    def reconnection_list(self, reconnection_list):
        """Sets the reconnection_list of this DisconnectionReconnection.

        Массив данных по возобновлению

        :param reconnection_list: The reconnection_list of this DisconnectionReconnection.
        :type reconnection_list: List[DisconnectionReconnectionReconnectionListInner]
        """

        self._reconnection_list = reconnection_list
