# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server.models.end_device_request_body_params import EndDeviceRequestBodyParams
from openapi_server.models.service import Service
from openapi_server import util


class EndDeviceRequestBody(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, service: Service=None, params: EndDeviceRequestBodyParams=None):
        """EndDeviceRequestBody - a model defined in OpenAPI

        :param service: The service of this EndDeviceRequestBody.
        :param params: The params of this EndDeviceRequestBody.
        """
        self.openapi_types = {
            'service': Service,
            'params': EndDeviceRequestBodyParams
        }

        self.attribute_map = {
            'service': 'Service',
            'params': 'Params'
        }

        self._service = service
        self._params = params

    @classmethod
    def from_dict(cls, dikt: dict) -> 'EndDeviceRequestBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The EndDevice_request_body of this EndDeviceRequestBody.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service(self):
        """Gets the service of this EndDeviceRequestBody.


        :return: The service of this EndDeviceRequestBody.
        :rtype: Service
        """
        return self._service

    @service.setter
    def service(self, service):
        """Sets the service of this EndDeviceRequestBody.


        :param service: The service of this EndDeviceRequestBody.
        :type service: Service
        """
        if service is None:
            raise ValueError("Invalid value for `service`, must not be `None`")

        self._service = service

    @property
    def params(self):
        """Gets the params of this EndDeviceRequestBody.


        :return: The params of this EndDeviceRequestBody.
        :rtype: EndDeviceRequestBodyParams
        """
        return self._params

    @params.setter
    def params(self, params):
        """Sets the params of this EndDeviceRequestBody.


        :param params: The params of this EndDeviceRequestBody.
        :type params: EndDeviceRequestBodyParams
        """
        if params is None:
            raise ValueError("Invalid value for `params`, must not be `None`")

        self._params = params
