# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class EndDevicesInnerMeasurePointsInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, description: str=None, type: str=None):
        """EndDevicesInnerMeasurePointsInner - a model defined in OpenAPI

        :param id: The id of this EndDevicesInnerMeasurePointsInner.
        :param description: The description of this EndDevicesInnerMeasurePointsInner.
        :param type: The type of this EndDevicesInnerMeasurePointsInner.
        """
        self.openapi_types = {
            'id': str,
            'description': str,
            'type': str
        }

        self.attribute_map = {
            'id': 'id',
            'description': 'description',
            'type': 'type'
        }

        self._id = id
        self._description = description
        self._type = type

    @classmethod
    def from_dict(cls, dikt: dict) -> 'EndDevicesInnerMeasurePointsInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The EndDevices_inner_MeasurePoints_inner of this EndDevicesInnerMeasurePointsInner.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this EndDevicesInnerMeasurePointsInner.


        :return: The id of this EndDevicesInnerMeasurePointsInner.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EndDevicesInnerMeasurePointsInner.


        :param id: The id of this EndDevicesInnerMeasurePointsInner.
        :type id: str
        """

        self._id = id

    @property
    def description(self):
        """Gets the description of this EndDevicesInnerMeasurePointsInner.


        :return: The description of this EndDevicesInnerMeasurePointsInner.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this EndDevicesInnerMeasurePointsInner.


        :param description: The description of this EndDevicesInnerMeasurePointsInner.
        :type description: str
        """

        self._description = description

    @property
    def type(self):
        """Gets the type of this EndDevicesInnerMeasurePointsInner.


        :return: The type of this EndDevicesInnerMeasurePointsInner.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this EndDevicesInnerMeasurePointsInner.


        :param type: The type of this EndDevicesInnerMeasurePointsInner.
        :type type: str
        """

        self._type = type
